<?php
/**
 * ACF Field Group Registration for Aus Real Estate News.
 *
 * Requires the Advanced Custom Fields (ACF) Pro plugin.
 * Registers field groups for articles, agent profiles, and agency profiles.
 */
class AusRealNews_ACF_Fields {

    public static function register(): void {
        if (!function_exists('acf_add_local_field_group')) {
            return;
        }

        self::register_article_fields();
        self::register_market_report_fields();
        self::register_agent_profile_fields();
        self::register_agency_profile_fields();
    }

    private static function register_article_fields(): void {
        acf_add_local_field_group([
            'key'      => 'group_ausrealnews_article',
            'title'    => 'Article Settings',
            'fields'   => [
                [
                    'key'          => 'field_source_urls',
                    'label'        => 'Source URLs',
                    'name'         => 'source_urls',
                    'type'         => 'url',
                    'instructions' => 'Research source URLs used for this article.',
                    'required'     => 0,
                    'multiple'     => true,
                    'wrapper'      => ['width' => '100'],
                ],
                [
                    'key'          => 'field_ai_pipeline_id',
                    'label'        => 'AI Pipeline ID',
                    'name'         => 'ai_pipeline_id',
                    'type'         => 'text',
                    'instructions' => 'n8n workflow/pipeline ID that generated this content.',
                    'required'     => 0,
                ],
                [
                    'key'          => 'field_risk_level',
                    'label'        => 'Risk Level',
                    'name'         => 'risk_level',
                    'type'         => 'select',
                    'choices'      => [
                        'Low'    => 'Low',
                        'Medium' => 'Medium',
                        'High'   => 'High',
                    ],
                    'default_value' => 'Low',
                    'required'      => 0,
                ],
                [
                    'key'          => 'field_is_ai_generated',
                    'label'        => 'Is AI Generated',
                    'name'         => 'is_ai_generated',
                    'type'         => 'true_false',
                    'instructions' => 'Whether this content was generated by AI.',
                    'default_value' => 0,
                    'required'      => 0,
                ],
            ],
            'location' => [
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'post',
                    ],
                ],
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'suburb_guide',
                    ],
                ],
                [
                    [
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'policy_update',
                    ],
                ],
            ],
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
        ]);
    }

    private static function register_market_report_fields(): void {
        acf_add_local_field_group([
            'key'    => 'group_ausrealnews_market_report',
            'title'  => 'Market Report Fields',
            'fields' => [
                [
                    'key'   => 'field_key_metrics',
                    'label' => 'Key Metrics',
                    'name'  => 'key_metrics',
                    'type'  => 'group',
                    'fields' => [
                        [
                            'key'          => 'field_median_price',
                            'label'        => 'Median Price',
                            'name'         => 'median_price',
                            'type'         => 'number',
                            'instructions' => 'Median property price in AUD.',
                            'required'     => 1,
                            'min'          => 0,
                        ],
                        [
                            'key'          => 'field_yoy_change',
                            'label'        => 'YoY Change (%)',
                            'name'         => 'yoy_change',
                            'type'         => 'number',
                            'instructions' => 'Year-on-year percentage change.',
                            'required'     => 0,
                            'min'          => -100,
                            'max'          => 100,
                            'step'         => 0.1,
                        ],
                        [
                            'key'          => 'field_vacancy_rate',
                            'label'        => 'Vacancy Rate (%)',
                            'name'         => 'vacancy_rate',
                            'type'         => 'number',
                            'instructions' => 'Current rental vacancy rate.',
                            'required'     => 0,
                            'min'          => 0,
                            'max'          => 100,
                            'step'         => 0.1,
                        ],
                        [
                            'key'          => 'field_days_on_market',
                            'label'        => 'Days on Market',
                            'name'         => 'days_on_market',
                            'type'         => 'number',
                            'instructions' => 'Average days property stays on market.',
                            'required'     => 0,
                            'min'          => 0,
                        ],
                    ],
                ],
                [
                    'key'          => 'field_source_urls_report',
                    'label'        => 'Source URLs',
                    'name'         => 'source_urls',
                    'type'         => 'url',
                    'instructions' => 'Data sources for this report.',
                    'multiple'     => true,
                ],
                [
                    'key'          => 'field_risk_level_report',
                    'label'        => 'Risk Level',
                    'name'         => 'risk_level',
                    'type'         => 'select',
                    'choices'      => ['Low' => 'Low', 'Medium' => 'Medium', 'High' => 'High'],
                    'default_value' => 'Low',
                ],
                [
                    'key'   => 'field_is_ai_generated_report',
                    'label' => 'Is AI Generated',
                    'name'  => 'is_ai_generated',
                    'type'  => 'true_false',
                ],
            ],
            'location' => [
                [['param' => 'post_type', 'operator' => '==', 'value' => 'market_report']],
            ],
        ]);
    }

    private static function register_agent_profile_fields(): void {
        acf_add_local_field_group([
            'key'    => 'group_ausrealnews_agent',
            'title'  => 'Agent Profile',
            'fields' => [
                [
                    'key'          => 'field_headline',
                    'label'        => 'Headline',
                    'name'         => 'headline',
                    'type'         => 'text',
                    'instructions' => 'Professional headline (e.g., Senior Property Analyst).',
                    'required'     => 1,
                ],
                [
                    'key'          => 'field_bio',
                    'label'        => 'Bio',
                    'name'         => 'bio',
                    'type'         => 'textarea',
                    'instructions' => 'Agent biography.',
                    'required'     => 1,
                ],
                [
                    'key'          => 'field_service_area',
                    'label'        => 'Service Area',
                    'name'         => 'service_area',
                    'type'         => 'text',
                    'instructions' => 'Geographic area of expertise.',
                ],
                [
                    'key'          => 'field_agency_id',
                    'label'        => 'Agency',
                    'name'         => 'agency_id',
                    'type'         => 'relationship',
                    'post_type'    => ['agency'],
                    'instructions' => 'Associated agency.',
                    'max'          => 1,
                ],
            ],
            'location' => [
                [['param' => 'user_role', 'operator' => '==', 'value' => 'agent_contributor']],
            ],
        ]);
    }

    private static function register_agency_profile_fields(): void {
        acf_add_local_field_group([
            'key'    => 'group_ausrealnews_agency',
            'title'  => 'Agency Profile',
            'fields' => [
                [
                    'key'          => 'field_agency_description',
                    'label'        => 'Description',
                    'name'         => 'description',
                    'type'         => 'textarea',
                    'instructions' => 'Agency description.',
                ],
                [
                    'key'          => 'field_website',
                    'label'        => 'Website',
                    'name'         => 'website',
                    'type'         => 'url',
                ],
                [
                    'key'          => 'field_social_links',
                    'label'        => 'Social Links',
                    'name'         => 'social_links',
                    'type'         => 'group',
                    'fields'       => [
                        [
                            'key'   => 'field_facebook',
                            'label' => 'Facebook',
                            'name'  => 'facebook',
                            'type'  => 'url',
                        ],
                        [
                            'key'   => 'field_instagram',
                            'label' => 'Instagram',
                            'name'  => 'instagram',
                            'type'  => 'url',
                        ],
                        [
                            'key'   => 'field_linkedin',
                            'label' => 'LinkedIn',
                            'name'  => 'linkedin',
                            'type'  => 'url',
                        ],
                    ],
                ],
            ],
            'location' => [
                [['param' => 'post_type', 'operator' => '==', 'value' => 'agency']],
            ],
        ]);
    }
}
